[ayu-dark]
ghostty = "Ayu"
zed = "Ayu Dark"

[ayu-light]
ghostty = "Ayu Light"
zed = "Ayu Light"

[ayu-mirage]
ghostty = "Ayu Mirage"
zed = "Ayu Mirage"

[catppuccin-macchiato]
ghostty = "Catppuccin Macchiato"
zed = "Catppuccin Macchiato"

[catppuccin-mocha]
ghostty = "Catppuccin Mocha"
zed = "Catppuccin Mocha"

[dracula]
ghostty = "Dracula"
zed = "Dracula"

[flexoki-dark]
ghostty = "Flexoki Dark"
zed = "Flexoki Dark"

[flexoki-light]
ghostty = "Flexoki Light"
zed = "Flexoki Light"

[github-dark]
ghostty = "GitHub Dark"
zed = "GitHub Dark"

[github-light]
ghostty = "GitHub Light Default"
zed = "GitHub Light"

[gruvbox-dark]
ghostty = "Gruvbox Dark"
zed = "Gruvbox Dark"

[gruvbox-dark-hard]
ghostty = "Gruvbox Dark Hard"
zed = "Gruvbox Dark Hard"

[gruvbox-light]
ghostty = "Gruvbox Light"
zed = "Gruvbox Light"

[gruvbox-light-hard]
ghostty = "Gruvbox Light Hard"
zed = "Gruvbox Light Hard"

[kanagawa]
ghostty = "Kanagawa Wave"
zed = "Kanagawa"

[kanagawa-wave]
ghostty = "Kanagawa Wave"
zed = "Kanagawa"

[matte-black]
ghostty = "Matte Black"
zed = "Matte Black"

[night-owl]
ghostty = "Night Owl"
zed = "Night Owl"

[nord]
ghostty = "Nord"
zed = "Nord"

[rose-pine]
ghostty = "Rose Pine"
zed = "Rosé Pine"

[rose-pine-dawn]
ghostty = "Rose Pine Dawn"
zed = "Rosé Pine Dawn"

[rose-pine-moon]
ghostty = "Rose Pine Moon"
zed = "Rosé Pine Moon"

[solarized-dark]
ghostty = "Solarized Dark Higher Contrast"
zed = "Solarized"

[solarized-light]
ghostty = "Builtin Solarized Light"
zed = "Solarized"

[tokyo-night]
ghostty = "TokyoNight"
zed = "Tokyo Night"

[tokyonight]
ghostty = "TokyoNight"
zed = "Tokyo Night"

[tokyonight-storm]
ghostty = "TokyoNight Storm"
zed = "Tokyo Night"
